/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    ColorPicker: typeof import('./src/components/ColorPicker.vue')['default']
    ComponentList: typeof import('./src/components/ComponentList.vue')['default']
    EditWrapper: typeof import('./src/components/EditWrapper.vue')['default']
    LText: typeof import('./src/components/LText.vue')['default']
    PropsTable: typeof import('./src/components/PropsTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
